// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/.well-known/appspecific/com.chrome.devtools.json": {
    params: {};
  };
  "/home": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/verify-email": {
    params: {};
  };
  "/support-page": {
    params: {};
  };
  "/terms-of-service": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/search-results": {
    params: {};
  };
  "/sports": {
    params: {};
  };
  "/Profile": {
    params: {};
  };
  "/withdrawal": {
    params: {};
  };
  "/deposit": {
    params: {};
  };
  "/bets": {
    params: {};
  };
  "/support": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/.well-known/appspecific/com.chrome.devtools.json" | "/home" | "/login" | "/register" | "/verify-email" | "/support-page" | "/terms-of-service" | "/about" | "/search-results" | "/sports" | "/Profile" | "/withdrawal" | "/deposit" | "/bets" | "/support" | "/*";
  };
  "./routes/index.jsx": {
    id: "routes/index";
    page: "/";
  };
  "./routes/devtools.jsx": {
    id: "routes/devtools";
    page: "/.well-known/appspecific/com.chrome.devtools.json";
  };
  "./routes/home.jsx": {
    id: "routes/home";
    page: "/home";
  };
  "./routes/login.jsx": {
    id: "routes/login";
    page: "/login";
  };
  "./routes/register.jsx": {
    id: "routes/register";
    page: "/register";
  };
  "./routes/verify-email.jsx": {
    id: "routes/verify-email";
    page: "/verify-email";
  };
  "./routes/support-page.jsx": {
    id: "routes/support-page";
    page: "/support-page";
  };
  "./routes/terms-of-service.jsx": {
    id: "routes/terms-of-service";
    page: "/terms-of-service";
  };
  "./routes/about.jsx": {
    id: "routes/about";
    page: "/about";
  };
  "./routes/search-results.jsx": {
    id: "routes/search-results";
    page: "/search-results";
  };
  "./routes/protected/sports.jsx": {
    id: "routes/protected/sports";
    page: "/sports";
  };
  "./routes/protected/profile.jsx": {
    id: "routes/protected/profile";
    page: "/Profile";
  };
  "./routes/protected/withdrawal.jsx": {
    id: "routes/protected/withdrawal";
    page: "/withdrawal";
  };
  "./routes/protected/deposit.jsx": {
    id: "routes/protected/deposit";
    page: "/deposit";
  };
  "./routes/protected/bets.jsx": {
    id: "routes/protected/bets";
    page: "/bets";
  };
  "./routes/protected/support.jsx": {
    id: "routes/protected/support";
    page: "/support";
  };
  "./routes/404page.jsx": {
    id: "routes/404page";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/index": typeof import("./app/./routes/index.jsx");
  "routes/devtools": typeof import("./app/./routes/devtools.jsx");
  "routes/home": typeof import("./app/./routes/home.jsx");
  "routes/login": typeof import("./app/./routes/login.jsx");
  "routes/register": typeof import("./app/./routes/register.jsx");
  "routes/verify-email": typeof import("./app/./routes/verify-email.jsx");
  "routes/support-page": typeof import("./app/./routes/support-page.jsx");
  "routes/terms-of-service": typeof import("./app/./routes/terms-of-service.jsx");
  "routes/about": typeof import("./app/./routes/about.jsx");
  "routes/search-results": typeof import("./app/./routes/search-results.jsx");
  "routes/protected/sports": typeof import("./app/./routes/protected/sports.jsx");
  "routes/protected/profile": typeof import("./app/./routes/protected/profile.jsx");
  "routes/protected/withdrawal": typeof import("./app/./routes/protected/withdrawal.jsx");
  "routes/protected/deposit": typeof import("./app/./routes/protected/deposit.jsx");
  "routes/protected/bets": typeof import("./app/./routes/protected/bets.jsx");
  "routes/protected/support": typeof import("./app/./routes/protected/support.jsx");
  "routes/404page": typeof import("./app/./routes/404page.jsx");
};