// api/generateReceiptPDF.js
import { jsPDF } from "jspdf";

export function generateReceiptPDF(receipt) {
  const doc = new jsPDF();

  doc.setFont("Helvetica", "bold");
  doc.setFontSize(18);
  doc.text("Bet Receipt", 20, 20);

  doc.setFont("Helvetica", "normal");
  doc.setFontSize(12);

  doc.text(`Receipt ID: ${receipt.receiptId}`, 20, 40);
  doc.text(`User: ${receipt.user}`, 20, 50);
  doc.text(`Event: ${receipt.event}`, 20, 60);
  doc.text(`Market: ${receipt.market}`, 20, 70);
  doc.text(`Odds: ${receipt.odds}`, 20, 80);
  doc.text(`Stake: ${receipt.stake}`, 20, 90);
  doc.text(`Potential Win: ${receipt.potentialWin}`, 20, 100);
  doc.text(`Status: ${receipt.status}`, 20, 110);

  // Footer
  doc.setFontSize(10);
  doc.text("Generated by ClutchDen", 20, 140);

  doc.save(`Receipt_${receipt.receiptId}.pdf`);
}
